//
//  WNDailyPlan.swift
//  What Now?
//

import Foundation
import SwiftData

/// A complete plan for a single day, containing ordered schedule blocks.
@Model
final class WNDailyPlan {
    var id: UUID = UUID()
    var date: Date = Date()
    var createdAt: Date = Date()
    var isAutoGenerated: Bool = false
    var reflectionNote: String?

    @Relationship(deleteRule: .cascade, inverse: \WNScheduleBlock.dailyPlan)
    var blocks: [WNScheduleBlock] = []

    // MARK: - Computed Properties

    /// Blocks sorted by start time.
    var sortedBlocks: [WNScheduleBlock] {
        blocks.sorted { $0.startTime < $1.startTime }
    }

    /// Total scheduled minutes (excluding free time).
    var totalScheduledMinutes: Int {
        blocks
            .filter { $0.blockTypeEnum != .freeTime }
            .reduce(0) { $0 + $1.durationMinutes }
    }

    /// Total free time minutes.
    var totalFreeMinutes: Int {
        blocks
            .filter { $0.blockTypeEnum == .freeTime }
            .reduce(0) { $0 + $1.durationMinutes }
    }

    // MARK: - Init

    init(date: Date, isAutoGenerated: Bool = false) {
        self.id = UUID()
        self.date = Calendar.current.startOfDay(for: date)
        self.createdAt = Date()
        self.isAutoGenerated = isAutoGenerated
    }
}
