//
//  PlanService.swift
//  What Now?
//

import Foundation
import SwiftData

/// Creates a lightweight, editable daily plan from tasks and optional routines.
@Observable
final class PlanService {
    private let context: ModelContext
    private let taskService: TaskService
    private let preferenceService: PreferenceService

    init(context: ModelContext, taskService: TaskService, preferenceService: PreferenceService) {
        self.context = context
        self.taskService = taskService
        self.preferenceService = preferenceService
    }

    func plan(for date: Date) -> WNDailyPlan? {
        let day = Calendar.current.startOfDay(for: date)
        let descriptor = FetchDescriptor<WNDailyPlan>(predicate: #Predicate { $0.date == day })
        return try? context.fetch(descriptor).first
    }

    @discardableResult
    func generatePlan(for date: Date = .now) -> WNDailyPlan {
        let calendar = Calendar.current
        let day = calendar.startOfDay(for: date)
        let plan = plan(for: day) ?? {
            let newPlan = WNDailyPlan(date: day, isAutoGenerated: true)
            context.insert(newPlan)
            return newPlan
        }()

        // Replanning replaces only generated blocks; it never changes tasks or routines.
        for block in plan.blocks {
            context.delete(block)
        }

        let profile = preferenceService.profile
        let dayStart = calendar.date(bySettingHour: profile.dayStartHour, minute: 0, second: 0, of: day) ?? day
        let dayEnd = calendar.date(bySettingHour: profile.dayEndHour, minute: 0, second: 0, of: day) ?? day.addingTimeInterval(.hours(16))
        let planningEnd = dayEnd.addingTimeInterval(.minutes(-60)) // preserves a real buffer at day's end
        var occupied: [(Date, Date)] = []

        let routineDescriptor = FetchDescriptor<WNRoutine>()
        let routines = ((try? context.fetch(routineDescriptor)) ?? [])
            .filter { $0.isActive(on: day) }
            .sorted { $0.preferredHour < $1.preferredHour }

        for routine in routines {
            let requested = calendar.date(bySettingHour: routine.preferredHour, minute: routine.preferredMinute, second: 0, of: day) ?? dayStart
            let start = nextAvailableSlot(after: max(requested, dayStart), duration: routine.estimatedMinutes, occupied: occupied, latest: planningEnd)
            guard let start else { continue }
            let end = start.addingTimeInterval(.minutes(routine.estimatedMinutes))
            insertBlock(date: day, start: start, end: end, title: routine.name, type: .routine, routine: routine, plan: plan)
            occupied.append((start, end))
        }

        let tasks = taskService.pendingTasks(for: day).sorted { lhs, rhs in
            if lhs.priorityEnum.sortOrder != rhs.priorityEnum.sortOrder {
                return lhs.priorityEnum.sortOrder < rhs.priorityEnum.sortOrder
            }
            return (lhs.deadline ?? .distantFuture) < (rhs.deadline ?? .distantFuture)
        }
        let maximumPlannedMinutes = Int(dayEnd.timeIntervalSince(dayStart) / 60 * 0.7)
        var taskMinutes = 0

        for task in tasks {
            let duration = task.effectiveEstimatedMinutes
            guard taskMinutes + duration <= maximumPlannedMinutes else { continue }
            let preferredStart = startDate(for: task, on: day, fallback: dayStart)
            guard let start = nextAvailableSlot(after: preferredStart, duration: duration, occupied: occupied, latest: planningEnd) else { continue }
            let end = start.addingTimeInterval(.minutes(duration))
            insertBlock(date: day, start: start, end: end, title: task.title, type: .task, task: task, plan: plan)
            occupied.append((start, end))
            taskMinutes += duration
        }

        plan.isAutoGenerated = true
        try? context.save()
        return plan
    }

    private func startDate(for task: WNTask, on day: Date, fallback: Date) -> Date {
        guard let preferred = task.preferredTimeEnum else { return fallback }
        return Calendar.current.date(bySettingHour: preferred.hourRange.lowerBound, minute: 0, second: 0, of: day) ?? fallback
    }

    private func nextAvailableSlot(after requested: Date, duration: Int, occupied: [(Date, Date)], latest: Date) -> Date? {
        var candidate = requested
        let sorted = occupied.sorted { $0.0 < $1.0 }
        for (start, end) in sorted where candidate < latest {
            let candidateEnd = candidate.addingTimeInterval(.minutes(duration))
            if candidateEnd <= start { break }
            if candidate < end { candidate = end.addingTimeInterval(.minutes(10)) }
        }
        return candidate.addingTimeInterval(.minutes(duration)) <= latest ? candidate : nil
    }

    private func insertBlock(
        date: Date, start: Date, end: Date, title: String, type: ScheduleBlockType,
        task: WNTask? = nil, routine: WNRoutine? = nil, plan: WNDailyPlan
    ) {
        let block = WNScheduleBlock(date: date, startTime: start, endTime: end, title: title, blockType: type, linkedTask: task, linkedRoutine: routine)
        block.dailyPlan = plan
        context.insert(block)
    }
    
    // MARK: - AI Replanning

    func applyProposedPlan(_ blocks: [ProposedBlock]) {
        let day = Calendar.current.startOfDay(for: .now)
        let plan = plan(for: day) ?? {
            let newPlan = WNDailyPlan(date: day, isAutoGenerated: true)
            context.insert(newPlan)
            return newPlan
        }()

        // Clear existing blocks
        for block in plan.blocks {
            context.delete(block)
        }

        let formatter = ISO8601DateFormatter()
        for b in blocks {
            guard let startTime = formatter.date(from: b.startTimeIso) else { continue }
            let endTime = startTime.addingTimeInterval(.minutes(b.durationMinutes))
            insertBlock(date: day, start: startTime, end: endTime, title: b.title, type: .task, plan: plan)
        }

        plan.isAutoGenerated = true
        try? context.save()
    }

    func applyModifications(_ actions: [PlanModification]) {
        guard let plan = plan(for: .now) else { return }

        let formatter = ISO8601DateFormatter()
        
        for action in actions {
            // Find the closest matching block
            if let target = plan.blocks.first(where: { $0.title.lowercased().contains(action.originalTitleFragment.lowercased()) }) {
                if let newStartIso = action.newStartTimeIso, let newStart = formatter.date(from: newStartIso) {
                    target.startTime = newStart
                    target.endTime = newStart.addingTimeInterval(.minutes(action.newDurationMinutes ?? target.durationMinutes))
                } else if let newDuration = action.newDurationMinutes {
                    target.endTime = target.startTime.addingTimeInterval(.minutes(newDuration))
                }
            }
        }
        
        try? context.save()
    }
}
